[workspace]
members = [
    "crates/stitchy",
    "crates/stitchy-core"
]
default-members = ["crates/stitchy"]

[workspace.dependencies]
clap = { version = "4.1.11", default-features = false, features = ["std", "derive"] }
