[package]
name = "stitchy"
version = "0.1.2"
authors = ["Thomas Reichert"]
edition = "2018"

[dependencies]
structopt = { version = "0.3.3", default-features = false }
image = { version = "0.23.4", default-features = false, features = ["jpeg", "png", "gif", "bmp"] }
