[workspace]
members = [
    "crates/stitchy",
    "crates/stitchy-core"
]
default-members = ["crates/stitchy"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5", default-features = false, features = ["std", "derive"] }
